### ISSUE TITLE
good game but the control is so difficult , can not even carry the crates 

### ISSUE THREAD

**Issue by stickylab** [craigzeki/ConstructionChaos#1]
![image](https://github.com/craigzeki/ConstructionChaos/assets/87752832/a96fe598-6c8c-4df8-9963-4edfc81abc1d)

**Comment by stickylab** [comment]
ah now i know , its turn out i have to hold the crates ,ok thanks

**Comment by craigzeki** [comment]
Great to see you figured it out. The controls can take a little while to get used to,  but once you have it, they should be OK. I'll close the issue.
